SET C51INC=C:\Keil\C51\INC\Cygnal\;C:\Keil\C51\INC\
SET C51LIB=C:\Keil\C51\LIB
SET CPU_TYPE=C8051F133
SET CPU_VENDOR=Silicon Laboratories, Inc.
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x05F5E100
C:\Keil\C51\BIN\C51.EXE @loader.__i
C:\Keil\C51\BIN\C51.EXE @AT25160A.__i
C:\Keil\C51\BIN\C51.EXE @PCA953~1.__I
C:\Keil\C51\BIN\C51.EXE @mscbutil.__i
C:\Keil\C51\BIN\C51.EXE @mscbmain.__i
C:\Keil\C51\BIN\C51.EXE @SPI_HA~1.__I
C:\Keil\C51\BIN\C51.EXE @SMBUS_~1.__I
C:\Keil\C51\BIN\BL51.EXE @loader.lnp
"C:\Keil\C51\BIN\OH51.EXE" "loader" 
